In [1]:
import numpy as np

# 3

In [7]:
def sigmoid(x):
    return (1/(1+np.exp(-x)))



# 3.3.3

In [2]:
X = np.array([1,2])
X.shape

(2,)

In [3]:
W= np.array([[1,3,5],[2,4,6]])
W.shape

(2, 3)

In [5]:
np.dot(X,W)

array([ 5, 11, 17])

# 3.4.2

In [13]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1,0.2,0.3])
# print(B1.shape)
A1 = np.dot(X,W1)+B1
A1

array([0.3, 0.7, 1.1])

In [14]:
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [16]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])

A2 = np.dot(Z1,W2)+B2
A2

array([0.51615984, 1.21402696])

In [17]:
Z2 = sigmoid(A2)
Z2

array([0.62624937, 0.7710107 ])

In [18]:
W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2, W3) + B3

A3


array([0.31682708, 0.69627909])

## 소프트맥스함수 구현

In [19]:
a = np.array([0.3,2.9,4.0])

y= np.exp(a)
y

array([ 1.34985881, 18.17414537, 54.59815003])

In [20]:
sum_y = np.sum(y)

In [21]:
y/sum_y

array([0.01821127, 0.24519181, 0.73659691])

In [24]:
def softmax(a:np.array):
    c = np.max(a)
    exp_a = np.exp(a-c)
    exp_sum = np.sum(exp_a)
    y = exp_a/exp_sum
    return y

In [27]:
softmax(np.array([0.3,2.9,4])).sum()

1.0

## mnist 데이터셋

In [29]:
import os, sys
sys.path.append(os.pardir)

In [30]:
from dataset.mnist import load_mnist

In [35]:
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

In [36]:
t_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [34]:
print(x_train.shape)

(60000, 784)


In [37]:
from PIL import Image